import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    name: 'English',
    flag: '🇬🇧',
    dir: 'ltr',
    messages: 'Messages',
    searchChats: 'Search chats...',
    all: 'All',
    unread: 'Unread',
    groups: 'Groups',
    welcome: 'Welcome to SovrChats',
    selectChat: 'Select a conversation to start chatting',
    online: '● Online',
    offline: '○ Offline',
    blocked: '🚫 Blocked',
    typeMessage: 'Type a message...',
    unblockToSend: 'Unblock to send messages',
    noChats: 'No chats found 🔍',
    noMessages: 'No messages yet. Say hello! 👋',
    newGroup: 'New Group',
    status: 'Status',
    settings: 'Settings',
    profile: 'Profile',
    myStatus: 'My Status',
    tapToAdd: 'Tap to add status update',
    recentUpdates: 'Recent Updates',
    notifications: '🔔 Notifications',
    msgNotif: 'Message Notifications',
    msgNotifSub: 'Show alerts for new messages',
    sound: 'Sound',
    soundSub: 'Play sound on new message',
    vibration: 'Vibration',
    vibrationSub: 'Vibrate on notification',
    privacy: '🔒 Privacy',
    lastSeen: 'Last Seen',
    profilePhoto: 'Profile Photo',
    readReceipts: 'Read Receipts',
    appearance: '🎨 Appearance',
    darkMode: 'Dark Mode',
    darkModeActive: 'Dark theme active',
    lightModeActive: 'Light theme active',
    chatWallpaper: 'Chat Wallpaper',
    wallpaperSub: 'Customize chat background',
    change: 'Change',
    chatFeatures: '💬 Chat Features',
    disappearing: 'Disappearing Messages',
    disappearingSub: 'Auto-delete after 30 seconds',
    account: '⚠️ Account',
    appVersion: 'App Version',
    logout: 'Logout',
    logoutSub: 'Sign out of your account',
    language: '🌐 Language',
    selectLang: 'Select Language',
    contactInfo: 'Contact Info',
    pinChat: 'Pin Chat',
    unpinChat: 'Unpin Chat',
    mute: 'Mute',
    unmute: 'Unmute',
    clearMessages: 'Clear Messages',
    disappearingMsgs: 'Disappearing Msgs',
    blockContact: 'Block Contact',
    unblock: 'Unblock',
    everyone: 'Everyone',
    contacts: 'Contacts',
    nobody: 'Nobody',
    yourName: 'Your Name',
    about: 'About',
    phone: 'Phone',
    avatarColor: 'Avatar Color',
    myStats: 'My Stats',
    messagesSent: 'Messages Sent',
    activeChats: 'Active Chats',
    pinnedChats: 'Pinned Chats',
    accountInfo: 'Account Info',
    quickSettings: 'Quick Settings',
    enterGroupName: 'Enter Group Name...',
    selectContacts: 'Select Contacts',
    createGroup: 'Create Group',
    post: 'Post',
    typeStatus: 'Type your status...',
    close: 'Close',
    done: 'Done',
    call: 'Call',
    video: 'Video',
    translating: 'Translating...',
    originalMsg: 'Show Original',
    translateMsg: 'Translate',
  },
  hi: {
    name: 'हिंदी',
    flag: '🇮🇳',
    dir: 'ltr',
    messages: 'संदेश',
    searchChats: 'चैट खोजें...',
    all: 'सब',
    unread: 'अपठित',
    groups: 'समूह',
    welcome: 'SovrChats में आपका स्वागत है',
    selectChat: 'चैट करने के लिए कोई बातचीत चुनें',
    online: '● ऑनलाइन',
    offline: '○ ऑफलाइन',
    blocked: '🚫 ब्लॉक किया',
    typeMessage: 'संदेश लिखें...',
    unblockToSend: 'संदेश भेजने के लिए अनब्लॉक करें',
    noChats: 'कोई चैट नहीं मिली 🔍',
    noMessages: 'अभी कोई संदेश नहीं। नमस्ते कहें! 👋',
    newGroup: 'नया समूह',
    status: 'स्टेटस',
    settings: 'सेटिंग्स',
    profile: 'प्रोफ़ाइल',
    myStatus: 'मेरा स्टेटस',
    tapToAdd: 'स्टेटस जोड़ने के लिए टैप करें',
    recentUpdates: 'हाल के अपडेट',
    notifications: '🔔 सूचनाएं',
    msgNotif: 'संदेश सूचनाएं',
    msgNotifSub: 'नए संदेशों के लिए अलर्ट दिखाएं',
    sound: 'ध्वनि',
    soundSub: 'नए संदेश पर ध्वनि बजाएं',
    vibration: 'कंपन',
    vibrationSub: 'सूचना पर कंपन करें',
    privacy: '🔒 गोपनीयता',
    lastSeen: 'अंतिम बार देखा',
    profilePhoto: 'प्रोफ़ाइल फ़ोटो',
    readReceipts: 'पढ़ने की पुष्टि',
    appearance: '🎨 दिखावट',
    darkMode: 'डार्क मोड',
    darkModeActive: 'डार्क थीम चालू',
    lightModeActive: 'लाइट थीम चालू',
    chatWallpaper: 'चैट वॉलपेपर',
    wallpaperSub: 'चैट की पृष्ठभूमि बदलें',
    change: 'बदलें',
    chatFeatures: '💬 चैट सुविधाएं',
    disappearing: 'गायब होने वाले संदेश',
    disappearingSub: '30 सेकंड बाद अपने आप मिटें',
    account: '⚠️ अकाउंट',
    appVersion: 'ऐप संस्करण',
    logout: 'लॉग आउट',
    logoutSub: 'अपने अकाउंट से बाहर निकलें',
    language: '🌐 भाषा',
    selectLang: 'भाषा चुनें',
    contactInfo: 'संपर्क जानकारी',
    pinChat: 'चैट पिन करें',
    unpinChat: 'चैट अनपिन करें',
    mute: 'म्यूट करें',
    unmute: 'अनम्यूट करें',
    clearMessages: 'संदेश हटाएं',
    disappearingMsgs: 'गायब संदेश',
    blockContact: 'ब्लॉक करें',
    unblock: 'अनब्लॉक करें',
    everyone: 'सभी',
    contacts: 'संपर्क',
    nobody: 'कोई नहीं',
    yourName: 'आपका नाम',
    about: 'परिचय',
    phone: 'फ़ोन',
    avatarColor: 'अवतार रंग',
    myStats: 'मेरे आँकड़े',
    messagesSent: 'भेजे गए संदेश',
    activeChats: 'सक्रिय चैट',
    pinnedChats: 'पिन की गई चैट',
    accountInfo: 'अकाउंट जानकारी',
    quickSettings: 'त्वरित सेटिंग्स',
    enterGroupName: 'समूह का नाम दर्ज करें...',
    selectContacts: 'संपर्क चुनें',
    createGroup: 'समूह बनाएं',
    post: 'पोस्ट करें',
    typeStatus: 'स्टेटस लिखें...',
    close: 'बंद करें',
    done: 'हो गया',
    call: 'कॉल',
    video: 'वीडियो',
    translating: 'अनुवाद हो रहा है...',
    originalMsg: 'मूल दिखाएं',
    translateMsg: 'अनुवाद करें',
  },
  ur: {
    name: 'اردو',
    flag: '🇵🇰',
    dir: 'rtl',
    messages: 'پیغامات',
    searchChats: 'چیٹ تلاش کریں...',
    all: 'سب',
    unread: 'نہ پڑھے',
    groups: 'گروپس',
    welcome: 'SovrChats میں خوش آمدید',
    selectChat: 'بات چیت شروع کرنے کے لیے کوئی گفتگو منتخب کریں',
    online: '● آن لائن',
    offline: '○ آف لائن',
    blocked: '🚫 بلاک',
    typeMessage: 'پیغام لکھیں...',
    unblockToSend: 'پیغام بھیجنے کے لیے انبلاک کریں',
    noChats: 'کوئی چیٹ نہیں ملی 🔍',
    noMessages: 'ابھی کوئی پیغام نہیں۔ سلام کریں! 👋',
    newGroup: 'نیا گروپ',
    status: 'اسٹیٹس',
    settings: 'ترتیبات',
    profile: 'پروفائل',
    myStatus: 'میرا اسٹیٹس',
    tapToAdd: 'اسٹیٹس شامل کرنے کے لیے ٹیپ کریں',
    recentUpdates: 'حالیہ اپڈیٹس',
    notifications: '🔔 اطلاعات',
    msgNotif: 'پیغام اطلاعات',
    msgNotifSub: 'نئے پیغامات کے لیے الرٹ دکھائیں',
    sound: 'آواز',
    soundSub: 'نئے پیغام پر آواز بجائیں',
    vibration: 'وائبریشن',
    vibrationSub: 'اطلاع پر وائبریٹ کریں',
    privacy: '🔒 رازداری',
    lastSeen: 'آخری بار دیکھا',
    profilePhoto: 'پروفائل تصویر',
    readReceipts: 'پڑھنے کی تصدیق',
    appearance: '🎨 ظاہری شکل',
    darkMode: 'ڈارک موڈ',
    darkModeActive: 'ڈارک تھیم فعال',
    lightModeActive: 'لائٹ تھیم فعال',
    chatWallpaper: 'چیٹ والپیپر',
    wallpaperSub: 'چیٹ کا پس منظر تبدیل کریں',
    change: 'تبدیل کریں',
    chatFeatures: '💬 چیٹ خصوصیات',
    disappearing: 'غائب ہونے والے پیغامات',
    disappearingSub: '30 سیکنڈ بعد خود بخود حذف',
    account: '⚠️ اکاؤنٹ',
    appVersion: 'ایپ ورژن',
    logout: 'لاگ آؤٹ',
    logoutSub: 'اپنے اکاؤنٹ سے باہر نکلیں',
    language: '🌐 زبان',
    selectLang: 'زبان منتخب کریں',
    contactInfo: 'رابطہ معلومات',
    pinChat: 'چیٹ پن کریں',
    unpinChat: 'چیٹ انپن کریں',
    mute: 'خاموش کریں',
    unmute: 'آن کریں',
    clearMessages: 'پیغامات حذف کریں',
    disappearingMsgs: 'غائب پیغامات',
    blockContact: 'بلاک کریں',
    unblock: 'انبلاک کریں',
    everyone: 'سب',
    contacts: 'رابطے',
    nobody: 'کوئی نہیں',
    yourName: 'آپ کا نام',
    about: 'تعارف',
    phone: 'فون',
    avatarColor: 'اوتار رنگ',
    myStats: 'میرے اعداد',
    messagesSent: 'بھیجے گئے پیغامات',
    activeChats: 'فعال چیٹس',
    pinnedChats: 'پن کی گئی چیٹس',
    accountInfo: 'اکاؤنٹ معلومات',
    quickSettings: 'فوری ترتیبات',
    enterGroupName: 'گروپ کا نام درج کریں...',
    selectContacts: 'رابطے منتخب کریں',
    createGroup: 'گروپ بنائیں',
    post: 'پوسٹ کریں',
    typeStatus: 'اسٹیٹس لکھیں...',
    close: 'بند کریں',
    done: 'ہو گیا',
    call: 'کال',
    video: 'ویڈیو',
    translating: 'ترجمہ ہو رہا ہے...',
    originalMsg: 'اصل دکھائیں',
    translateMsg: 'ترجمہ کریں',
  },
  hinglish: {
    name: 'Hinglish',
    flag: '🇮🇳',
    dir: 'ltr',
    messages: 'Messages',
    searchChats: 'Chats dhundho...',
    all: 'Sab',
    unread: 'Nahi padha',
    groups: 'Groups',
    welcome: 'SovrChats mein aapka swagat hai',
    selectChat: 'Chat karne ke liye koi conversation select karo',
    online: '● Online hai',
    offline: '○ Offline hai',
    blocked: '🚫 Block kiya hua',
    typeMessage: 'Message likho...',
    unblockToSend: 'Message bhejne ke liye unblock karo',
    noChats: 'Koi chat nahi mili 🔍',
    noMessages: 'Abhi koi message nahi. Hello bolo! 👋',
    newGroup: 'Naya Group',
    status: 'Status',
    settings: 'Settings',
    profile: 'Profile',
    myStatus: 'Mera Status',
    tapToAdd: 'Status add karne ke liye tap karo',
    recentUpdates: 'Recent Updates',
    notifications: '🔔 Notifications',
    msgNotif: 'Message Notifications',
    msgNotifSub: 'Naye messages ke liye alert dikhao',
    sound: 'Awaaz',
    soundSub: 'Naye message pe awaaz bajao',
    vibration: 'Vibration',
    vibrationSub: 'Notification pe vibrate karo',
    privacy: '🔒 Privacy',
    lastSeen: 'Last Seen',
    profilePhoto: 'Profile Photo',
    readReceipts: 'Read Receipts',
    appearance: '🎨 Dikhaawat',
    darkMode: 'Dark Mode',
    darkModeActive: 'Dark theme chal rahi hai',
    lightModeActive: 'Light theme chal rahi hai',
    chatWallpaper: 'Chat Wallpaper',
    wallpaperSub: 'Chat ka background badlo',
    change: 'Badlo',
    chatFeatures: '💬 Chat Features',
    disappearing: 'Gayab hone wale Messages',
    disappearingSub: '30 second baad apne aap delete',
    account: '⚠️ Account',
    appVersion: 'App Version',
    logout: 'Logout karo',
    logoutSub: 'Apne account se bahar jao',
    language: '🌐 Bhasha',
    selectLang: 'Bhasha chuno',
    contactInfo: 'Contact Info',
    pinChat: 'Chat Pin karo',
    unpinChat: 'Chat Unpin karo',
    mute: 'Mute karo',
    unmute: 'Unmute karo',
    clearMessages: 'Messages hatao',
    disappearingMsgs: 'Gayab Messages',
    blockContact: 'Block karo',
    unblock: 'Unblock karo',
    everyone: 'Sabko',
    contacts: 'Contacts',
    nobody: 'Kisi ko nahi',
    yourName: 'Tumhara Naam',
    about: 'Baare mein',
    phone: 'Phone',
    avatarColor: 'Avatar ka Rang',
    myStats: 'Mere Stats',
    messagesSent: 'Bheje gaye Messages',
    activeChats: 'Active Chats',
    pinnedChats: 'Pinned Chats',
    accountInfo: 'Account Info',
    quickSettings: 'Quick Settings',
    enterGroupName: 'Group ka naam likho...',
    selectContacts: 'Contacts chuno',
    createGroup: 'Group banao',
    post: 'Post karo',
    typeStatus: 'Status likho...',
    close: 'Band karo',
    done: 'Ho gaya',
    call: 'Call karo',
    video: 'Video',
    translating: 'Translate ho raha hai...',
    originalMsg: 'Original dikhao',
    translateMsg: 'Translate karo',
  },
  pa: {
    name: 'ਪੰਜਾਬੀ',
    flag: '🇮🇳',
    dir: 'ltr',
    messages: 'ਸੁਨੇਹੇ',
    searchChats: 'ਚੈਟ ਲੱਭੋ...',
    all: 'ਸਭ',
    unread: 'ਨਾ ਪੜ੍ਹੇ',
    groups: 'ਗਰੁੱਪ',
    welcome: 'SovrChats ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ',
    selectChat: 'ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਕੋਈ ਗੱਲਬਾਤ ਚੁਣੋ',
    online: '● ਔਨਲਾਈਨ',
    offline: '○ ਔਫਲਾਈਨ',
    blocked: '🚫 ਬਲਾਕ',
    typeMessage: 'ਸੁਨੇਹਾ ਲਿਖੋ...',
    unblockToSend: 'ਸੁਨੇਹਾ ਭੇਜਣ ਲਈ ਅਨਬਲਾਕ ਕਰੋ',
    noChats: 'ਕੋਈ ਚੈਟ ਨਹੀਂ ਮਿਲੀ 🔍',
    noMessages: 'ਹਾਲੇ ਕੋਈ ਸੁਨੇਹਾ ਨਹੀਂ। ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਕਹੋ! 👋',
    newGroup: 'ਨਵਾਂ ਗਰੁੱਪ',
    status: 'ਸਟੇਟਸ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    myStatus: 'ਮੇਰਾ ਸਟੇਟਸ',
    tapToAdd: 'ਸਟੇਟਸ ਜੋੜਨ ਲਈ ਟੈਪ ਕਰੋ',
    recentUpdates: 'ਹਾਲੀਆ ਅੱਪਡੇਟ',
    notifications: '🔔 ਸੂਚਨਾਵਾਂ',
    msgNotif: 'ਸੁਨੇਹਾ ਸੂਚਨਾਵਾਂ',
    msgNotifSub: 'ਨਵੇਂ ਸੁਨੇਹਿਆਂ ਲਈ ਅਲਰਟ ਦਿਖਾਓ',
    sound: 'ਅਵਾਜ਼',
    soundSub: 'ਨਵੇਂ ਸੁਨੇਹੇ ਤੇ ਅਵਾਜ਼ ਵਜਾਓ',
    vibration: 'ਕੰਬਣੀ',
    vibrationSub: 'ਸੂਚਨਾ ਤੇ ਕੰਬਣੀ ਕਰੋ',
    privacy: '🔒 ਗੋਪਨੀਯਤਾ',
    lastSeen: 'ਆਖਰੀ ਵਾਰ ਦੇਖਿਆ',
    profilePhoto: 'ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ',
    readReceipts: 'ਪੜ੍ਹਨ ਦੀ ਪੁਸ਼ਟੀ',
    appearance: '🎨 ਦਿੱਖ',
    darkMode: 'ਡਾਰਕ ਮੋਡ',
    darkModeActive: 'ਡਾਰਕ ਥੀਮ ਚਾਲੂ',
    lightModeActive: 'ਲਾਈਟ ਥੀਮ ਚਾਲੂ',
    chatWallpaper: 'ਚੈਟ ਵਾਲਪੇਪਰ',
    wallpaperSub: 'ਚੈਟ ਦੀ ਪਿੱਠਭੂਮੀ ਬਦਲੋ',
    change: 'ਬਦਲੋ',
    chatFeatures: '💬 ਚੈਟ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    disappearing: 'ਗਾਇਬ ਹੋਣ ਵਾਲੇ ਸੁਨੇਹੇ',
    disappearingSub: '30 ਸਕਿੰਟ ਬਾਅਦ ਆਪੇ ਮਿਟੋ',
    account: '⚠️ ਖਾਤਾ',
    appVersion: 'ਐਪ ਵਰਜ਼ਨ',
    logout: 'ਲੌਗਆਊਟ',
    logoutSub: 'ਆਪਣੇ ਖਾਤੇ ਤੋਂ ਬਾਹਰ ਜਾਓ',
    language: '🌐 ਭਾਸ਼ਾ',
    selectLang: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    contactInfo: 'ਸੰਪਰਕ ਜਾਣਕਾਰੀ',
    pinChat: 'ਚੈਟ ਪਿੰਨ ਕਰੋ',
    unpinChat: 'ਚੈਟ ਅਨਪਿੰਨ ਕਰੋ',
    mute: 'ਮਿਊਟ ਕਰੋ',
    unmute: 'ਅਨਮਿਊਟ ਕਰੋ',
    clearMessages: 'ਸੁਨੇਹੇ ਹਟਾਓ',
    disappearingMsgs: 'ਗਾਇਬ ਸੁਨੇਹੇ',
    blockContact: 'ਬਲਾਕ ਕਰੋ',
    unblock: 'ਅਨਬਲਾਕ ਕਰੋ',
    everyone: 'ਸਭ',
    contacts: 'ਸੰਪਰਕ',
    nobody: 'ਕੋਈ ਨਹੀਂ',
    yourName: 'ਤੁਹਾਡਾ ਨਾਮ',
    about: 'ਬਾਰੇ ਵਿੱਚ',
    phone: 'ਫ਼ੋਨ',
    avatarColor: 'ਅਵਤਾਰ ਰੰਗ',
    myStats: 'ਮੇਰੇ ਅੰਕੜੇ',
    messagesSent: 'ਭੇਜੇ ਸੁਨੇਹੇ',
    activeChats: 'ਸਰਗਰਮ ਚੈਟਾਂ',
    pinnedChats: 'ਪਿੰਨ ਕੀਤੀਆਂ ਚੈਟਾਂ',
    accountInfo: 'ਖਾਤਾ ਜਾਣਕਾਰੀ',
    quickSettings: 'ਤੇਜ਼ ਸੈਟਿੰਗਾਂ',
    enterGroupName: 'ਗਰੁੱਪ ਦਾ ਨਾਮ ਦਾਖਲ ਕਰੋ...',
    selectContacts: 'ਸੰਪਰਕ ਚੁਣੋ',
    createGroup: 'ਗਰੁੱਪ ਬਣਾਓ',
    post: 'ਪੋਸਟ ਕਰੋ',
    typeStatus: 'ਸਟੇਟਸ ਲਿਖੋ...',
    close: 'ਬੰਦ ਕਰੋ',
    done: 'ਹੋ ਗਿਆ',
    call: 'ਕਾਲ',
    video: 'ਵੀਡੀਓ',
    translating: 'ਅਨੁਵਾਦ ਹੋ ਰਿਹਾ ਹੈ...',
    originalMsg: 'ਅਸਲ ਦਿਖਾਓ',
    translateMsg: 'ਅਨੁਵਾਦ ਕਰੋ',
  }
}

const LanguageContext = createContext()

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en')
  const t = translations[lang]
  const dir = translations[lang].dir

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir, translations }}>
      <div dir={dir}>
        {children}
      </div>
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
export default translations